### ISSUE TITLE
TokenExtraction Error

### ISSUE THREAD

**Issue by Ewwe** [juliand665/Recon-Bolt#1]
Hi, im using app on ios15 and since version 10 im getting TokenExtraction Error. Today i tried another account and its works. So can we somehow debug what different on my account  that i can log in ?

**Comment by juliand665** [comment]
Hi! Saw your email earlier. Thanks for coming here, this is certainly a good place to figure this out. Can you share a screenshot of the error?

**Comment by Ewwe** [comment]
![image](https://user-images.githubusercontent.com/7504761/127397912-7facc2e7-4142-4a39-92d4-0b19761c0aa8.png)

**Comment by juliand665** [comment]
Interesting! I'll add some better error display in the next update and then we should get more information out of this. I think I know where it's failing, but it would help to have some more information (which I'll be outputting).

**Comment by Ewwe** [comment]
Nice. Soon as i get new version ill update this issue

**Comment by juliand665** [comment]
Put out a new version! The screenshot should contain more helpful info now :)

**Comment by Ewwe** [comment]
Nice there is a full message


![Uploading 21B970BE-5510-4393-8445-A72B21A6688C.png…]()

**Comment by juliand665** [comment]
Ah, i see where I went wrong! Thanks. The fix is a single character lmao

**Comment by juliand665** [comment]
Fixed in https://github.com/juliand665/ValorantAPI/commit/9e86810f61c5ea1ad946ac381ff1ef4b2de07c89.

**Comment by juliand665** [comment]
I've already closed the issue, but do let me know if the new update (out now) fixes it :)

**Comment by Ewwe** [comment]
hi, i tried 

![242B65C1-F76B-4BDE-B718-68B40C23AE53](https://user-images.githubusercontent.com/7504761/127751308-85da6d8c-0d60-4c9b-b345-5d917e448008.png)

**Comment by juliand665** [comment]
Oh, interesting! Looks like I'll have to adjust my approach a slight bit. That error was actually really helpful, thanks :)

**Comment by juliand665** [comment]
New version's out—I didn't have it notify everyone this time though, so you'll have to check for it yourself.

**Comment by Ewwe** [comment]
I have availaible version 16 and still same soo…

**Comment by juliand665** [comment]
Huh, that's strange. Could you send another screenshot? It's possible the error looks mostly the same but is actually slightly different.

**Comment by juliand665** [comment]
Ah, I think I see the issue. You should have version 17 available! If you don't, I guess I really do have to notify everyone in order for them to even see the new build…

**Comment by Ewwe** [comment]
Now i tested out version 17 and its fixed and works like a charm.

**Comment by juliand665** [comment]
Glad to hear it! Thanks for helping out :)
