### ISSUE TITLE
Attack/Defender Pop up

### ISSUE THREAD

**Issue by Arivz02** [juliand665/Recon-Bolt#106]
Having an issue where i don’t see red team or blue team anymore after updating to pro not sure if that was a coincidence or not but it’s the main reason i use the app i like to know what side i’m starting on before i pick my agent

**Comment by AelinAshryverGalathynius** [comment]
That is a competitive advantage that even a blind and deaf person on the level of Helen Keller (if she wasn't lying) could notice.
It's been removed.

**Comment by juliand665** [comment]
Yeah, this was the last competitively questionable feature so I had to remove it. Sorry!
