### ISSUE TITLE
Friend list feature

### ISSUE THREAD

**Issue by caturbgs** [juliand665/Recon-Bolt#12]
I was just curious, is there any possibility to add a friend list feature (online, playing, offline, etc)? 
I'm not talking about further features like Send Message, Invite to party, Request to party, or remove a friend. Just a simple friend list feature.
I wish there are an API that covers it up. Thank you.

**Comment by QualmOnAcid** [comment]
Nope. it's not possible at the moment because friends are stored in the local api which means you can only access this api on the device you are playing valorant on.

**Comment by caturbgs** [comment]
Woah, just hope someday Riot will expose that API without the client😅. Anyway, thanks for the reply!
