### ISSUE TITLE
Development certificate

### ISSUE THREAD

**Issue by RamiAlzayat** [juliand665/Recon-Bolt#14]
Hey,
Is it possible to get a development certificate?
I would like to run the app locally on my mac and experiment with it (All local) no need for distribution access

 Thanks in advance :) great job btw

<img width="763" alt="Screenshot 2023-02-12 at 00 11 38" src="https://user-images.githubusercontent.com/18601660/218285006-62d744cd-9c9e-4503-9238-7d8e67b94a27.png">

**Comment by juliand665** [comment]
Unfortunately, I think the way Apple handles this means you need to change the identifiers to run it locally. Apart from that it should be fine; you can use the Find sidebar to check you haven't missed any occurrences.

**Comment by juliand665** [comment]
Or at least, that should work? Giving out development certificates seems unnecessary for this, I think.

**Comment by RamiAlzayat** [comment]
Thanks for the quick response :)
Changing the identifiers solved it.

**Comment by RamiAlzayat** [comment]
Just a question, is there any chance for getting banned using this app?

![image](https://user-images.githubusercontent.com/18601660/218285275-16b4005b-40d3-467d-b399-6226040a3e61.jpeg)

**Comment by juliand665** [comment]
They say stuff like that all the time, but have never contacted me and I don't know of anyone getting banned for it.
