### ISSUE TITLE
Can't "Add another Account"

### ISSUE THREAD

**Issue by tiandrew** [juliand665/Recon-Bolt#65]
It looks like I cannot add another account in the `Settings`. Is the option seemingly greyed out for a reason? I'd like to be able to check the daily shop for multiple accounts.

**Comment by juliand665** [comment]
Multiple accounts is a Pro feature, as listed in the sales pitch a little further down the Settings view :)

I figured the alternative was having the button be tappable and only then showing an alert, but that felt like I'd be tricking users. There's definitely room for improvement around that messaging though!
