### ISSUE TITLE
Feedback lmao

### ISSUE THREAD

**Issue by QualmOnAcid** [juliand665/Recon-Bolt#7]
Hey!

I've been using this app for a while now and i have to say that i never saw such a good app. It literally looks so clean, works smooth and the features that it gives are so cool! Just wanted to say that you did a very good job!

**Comment by juliand665** [comment]
Thanks! This means a lot :) The app has been really rewarding to work on; I just hope Riot see what you see in it and don't shut it down lol

**Comment by QualmOnAcid** [comment]
I really don't think they are gonna shut it down. I'm the creator of Elsify if you heard about it. It's a skin changer which uses the api to swap the items and they didn't shut that down so would make no sense

**Comment by juliand665** [comment]
Yeah, I'm just worried that when I release it on the App Store that'll start causing issues, but honestly it wouldn't make sense for them to go after that while ignoring websites.
