### ISSUE TITLE
Reconbolt Android

### ISSUE THREAD

**Issue by ZeyMax** [juliand665/Recon-Bolt#9]
Hi !
I wanted to know if in the future, this app will be available on Android and if yes, do you have a date for it ?

Thank you,
ZeyMax

**Comment by KillaBoi** [comment]
AFAIK no, if you read https://github.com/juliand665/Recon-Bolt#why-not-android you will see the reason as to why, also here is what julian posted in the discord

![image.jpg](https://i.imgur.com/sHAVo0V.png)

**Comment by ZeyMax** [comment]
Thank you for your help !
